

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ivan
 */
public class VtnAgendaCont2 extends javax.swing.JFrame {

    public String grupo;
    public String persona;
    public Nodo r;
    public Nodo arr[]= new Nodo[2];
    /**
     * Creates new form VtnAgendaCont2
     */
    public VtnAgendaCont2() {
        setTitle("Fecha");
        initComponents();
        bloquea();
    }
    public void bloquea()
    {
        if (r == null)
        {
            BtnE.setEnabled(false);
        } else
        {
            BtnE.setEnabled(true);
        }
    }
    public void actualiza()
    {
        r = Multilistas.busca(VtnPrincipal.r, grupo);
        r = r.getAbajo();
        r = Multilistas.busca(r, persona);
        r = r.getAbajo();
        Panel.removeAll();
        if (r != null)
        {
            Nodo aux = r;
            while (aux != null)
            {
                JButton boton = new JButton(aux.getEtq());
                Panel.add(boton);
                boton.addActionListener(new ActionListener()
                {
                    @Override
                    public void actionPerformed(ActionEvent e)
                    {
                        VtnChat chat = new VtnChat();
                        chat.grupo = grupo;
                        chat.persona = persona;
                        chat.fecha = boton.getText();
                        chat.archivo();
                        chat.setVisible(true);
                    }
                }
                );
                aux = aux.getSiguiente();
            }
        }
        Panel.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();
        BtnA = new javax.swing.JButton();
        BtnE = new javax.swing.JButton();
        BtnAt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        Panel.setLayout(new java.awt.GridLayout(0, 1, 0, 1));
        jScrollPane1.setViewportView(Panel);

        BtnA.setText("Añadir");
        BtnA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAMouseClicked(evt);
            }
        });

        BtnE.setText("Eliminar");
        BtnE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEMouseClicked(evt);
            }
        });

        BtnAt.setText("Atrás");
        BtnAt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnAt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnA, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(BtnE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAt)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnA)
                    .addComponent(BtnE))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAMouseClicked
        String s = "";
        s = JOptionPane.showInputDialog("Día agregar?");
        if (s == null)
        {
            s = "";
        }
        if (s.length() != 0)
        {
            if (Pattern.matches("^([0-2][0-9]|3[0-1])(\\/|-)(0[1-9]|1[0-2])\\2(\\d{4})$", s))
            {
                Archivo ar = new Archivo();
                Nodo aux = new Nodo(ar, s);
                String[] etqs = new String[3];
                etqs[0] = grupo;
                etqs[1] = persona;
                etqs[2] = s;
                VtnPrincipal.r = Multilistas.inserta(VtnPrincipal.r, aux, 0, etqs);
                actualiza();
                bloquea();
            } else
            {
                JOptionPane.showMessageDialog(null, "Formato no valido", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnAMouseClicked

    private void BtnEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEMouseClicked
        String s = "";
        s = JOptionPane.showInputDialog("Día a eliminar?");
        if (s == null)
        {
            s = "";
        }
        if (s.length() != 0)
        {
            if (Pattern.matches("^([0-2][0-9]|3[0-1])(\\/|-)(0[1-9]|1[0-2])\\2(\\d{4})$", s))
            {
                String[] etqs = new String[3];
                etqs[0] = grupo;
                etqs[1] = persona;
                etqs[2] = s;
                VtnPrincipal.r = Multilistas.elimina2(VtnPrincipal.r, 0, etqs);
                actualiza();
                bloquea();
            } else
            {
                JOptionPane.showMessageDialog(null, "Formato no valido", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_BtnEMouseClicked

    private void BtnAtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAtMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_BtnAtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAgendaCont2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAgendaCont2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAgendaCont2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAgendaCont2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnAgendaCont2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnA;
    private javax.swing.JButton BtnAt;
    private javax.swing.JButton BtnE;
    private javax.swing.JPanel Panel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
