/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ivan
 */
public class VtnAgendaCont1 extends javax.swing.JFrame {

    public Nodo r;
    public String grupo;
    public Nodo arr[]= new Nodo[2];
    /**
     * Creates new form VtnAgendaCont1
     */
    public VtnAgendaCont1() 
    {
        setTitle("Contactos");
        initComponents();
        actualiza();
        bloquea();
    }
    public void bloquea()
    {
        if (r == null)
        {
            BtnE.setEnabled(false);
            BtnM.setEnabled(false);
        } else
        {
            BtnE.setEnabled(true);
            BtnM.setEnabled(true);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();
        BtnA = new javax.swing.JButton();
        BtnE = new javax.swing.JButton();
        BtnAt = new javax.swing.JButton();
        BtnM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setLayout(new java.awt.GridLayout(0, 1, 0, 1));
        jScrollPane1.setViewportView(Panel);

        BtnA.setText("Añadir");
        BtnA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAMouseClicked(evt);
            }
        });

        BtnE.setText("Eliminar");
        BtnE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEMouseClicked(evt);
            }
        });

        BtnAt.setText("Atrás");
        BtnAt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAtMouseClicked(evt);
            }
        });

        BtnM.setText("Mover");
        BtnM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(BtnA, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(BtnM)
                .addGap(53, 53, 53)
                .addComponent(BtnE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BtnAt)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnE)
                    .addComponent(BtnA)
                    .addComponent(BtnM))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAMouseClicked
         String s = "";
        s = JOptionPane.showInputDialog(grupo + " que desea agregar");
        if (s == null)
        {
            s = "";
        }
        if (s.length() != 0)
        {
            Nodo aux = new Nodo(null, s);
            String[] etqs = new String[2];
            etqs[0] = grupo;
            etqs[1] = s;
            VtnPrincipal.r = Multilistas.inserta(VtnPrincipal.r, aux, 0, etqs);
            actualiza();
            bloquea();
        }
    }//GEN-LAST:event_BtnAMouseClicked

    private void BtnMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMMouseClicked
        String s = "";
        s = JOptionPane.showInputDialog("Inserta el contacto que  desea mover?");
        if (s == null)
        {
            s = "";
        }
        Nodo aux = r;
        boolean b = false;
        while (aux != null)
        {
            if (aux.getEtq().equals(s))
            {
                b = true;
            }
            aux = aux.getSiguiente();
        }
        if (!b)
        {
            JOptionPane.showMessageDialog(null, "No se encontro a la persona", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        } else
        {
            if (s.length() != 0)
            {
                String s2 = "";
                s2 = JOptionPane.showInputDialog("Categoria a mover");
                if (s2 == null)
                {
                    s2 = "";
                }
                aux = Multilistas.busca(VtnPrincipal.r, s2);
                if (aux != null)
                {
                    if (s2.length() != 0)
                    {
                        String[] etqsE = new String[2];
                        etqsE[0] = grupo;
                        etqsE[1] = s;
                        String[] etqsI = new String[2];
                        etqsI[0] = s2;
                        etqsI[1] = s;
                        VtnPrincipal.r = Multilistas.mueve(VtnPrincipal.r, 0, etqsE, etqsI);
                        bloquea();
                        actualiza();
                    }                    
                }else{
                    JOptionPane.showMessageDialog(null, "No se encontro la categoria", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        }
    }//GEN-LAST:event_BtnMMouseClicked

    private void BtnEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEMouseClicked
                                               
        String s = "";
        s = JOptionPane.showInputDialog("Seleccione el contacto que desea eliminar?");
        if (s == null)
        {
            s = "";
        }
        if (s.length() != 0)
        {
            String[] etqs = new String[2];
            etqs[0] = grupo;
            etqs[1] = s;
            VtnPrincipal.r = Multilistas.elimina2(VtnPrincipal.r, 0, etqs);
            actualiza();
            bloquea();
        }
    }//GEN-LAST:event_BtnEMouseClicked

    private void BtnAtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAtMouseClicked
         this.setVisible(false);
    }//GEN-LAST:event_BtnAtMouseClicked

    public void actualiza()
    {
        r = Multilistas.busca(VtnPrincipal.r, grupo);
        if(r != null)
        {
            r = r.getAbajo();
        }
        Panel.removeAll();
        if (r != null)
        {
            Nodo aux = r;
            while (aux != null)
            {
                JButton boton = new JButton(aux.getEtq());
                Panel.add(boton);
                boton.addActionListener(new ActionListener()
                {
                    @Override
                    public void actionPerformed(ActionEvent e)
                    {
                        VtnAgendaCont2 chat = new VtnAgendaCont2();
                        chat.grupo= grupo;
                        chat.persona = boton.getText();
                        chat.setVisible(true);
                        chat.actualiza();
                    }
                }
                );
                aux = aux.getSiguiente();
            }
        }
        Panel.updateUI();
    }
    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAgendaCont1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAgendaCont1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAgendaCont1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAgendaCont1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnAgendaCont1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnA;
    private javax.swing.JButton BtnAt;
    private javax.swing.JButton BtnE;
    private javax.swing.JButton BtnM;
    private javax.swing.JPanel Panel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
