
import static com.sun.org.apache.xerces.internal.impl.xpath.regex.CaseInsensitiveMap.get;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yo mero palomero
 */
public class VtnChat extends javax.swing.JFrame {

    /**
     * Creates new form VtnChat
     */
    String s = "";
    public Archivo ar;
    public Nodo r;

    public String grupo;
    public String persona;
    public String fecha;
    
    public VtnChat() 
    {
        initComponents();
        
    }
        String cad;
        FileInputStream archivoe;
        FileOutputStream archivos;
        public void archivo()
        {
            r = Multilistas.busca(VtnPrincipal.r, grupo);
            r = r.getAbajo();
            r = Multilistas.busca(r, persona);
            r= r.getAbajo();
            r = Multilistas.busca(r, fecha);
            if (r.getObj() != null)
            {
                ar= (Archivo) r.getObj();
                cad=ar.getCol().cadena();
                JTAC.setText(cad);
            } else
            {
                ar = new Archivo();
            }
        }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnEn2 = new javax.swing.JButton();
        BtnEn1 = new javax.swing.JButton();
        BtnMo1 = new javax.swing.JButton();
        BtnMo2 = new javax.swing.JButton();
        BtnBus1 = new javax.swing.JButton();
        BtnBus2 = new javax.swing.JButton();
        BtnOr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAC = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTA1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTA2 = new javax.swing.JTextArea();
        BtnMC = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BtnEn2.setText("Enviar");
        BtnEn2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnEn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEn2MouseClicked(evt);
            }
        });
        BtnEn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEn2ActionPerformed(evt);
            }
        });

        BtnEn1.setText("Enviar");
        BtnEn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEn1MouseClicked(evt);
            }
        });

        BtnMo1.setText("Mostrar");
        BtnMo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMo1MouseClicked(evt);
            }
        });
        BtnMo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMo1ActionPerformed(evt);
            }
        });

        BtnMo2.setText("Mostrar");
        BtnMo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMo2MouseClicked(evt);
            }
        });

        BtnBus1.setText("Buscar");
        BtnBus1.setActionCommand("");
        BtnBus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBus1ActionPerformed(evt);
            }
        });

        BtnBus2.setText("Buscar");
        BtnBus2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBus2MouseClicked(evt);
            }
        });

        BtnOr.setText("Ordenar");
        BtnOr.setActionCommand("");
        BtnOr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnOrMouseClicked(evt);
            }
        });

        JTAC.setEditable(false);
        JTAC.setColumns(20);
        JTAC.setRows(5);
        JTAC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTACKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(JTAC);

        JTA1.setColumns(20);
        JTA1.setRows(5);
        jScrollPane2.setViewportView(JTA1);

        JTA2.setColumns(20);
        JTA2.setRows(5);
        jScrollPane3.setViewportView(JTA2);

        BtnMC.setText("Mostrar conversación");
        BtnMC.setActionCommand("");
        BtnMC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMCMouseClicked(evt);
            }
        });
        BtnMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMCActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnMo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnBus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnEn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnOr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnMC))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BtnMo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnBus2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnEn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(65, 65, 65))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnEn2)
                            .addComponent(BtnEn1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnMo1)
                            .addComponent(BtnMo2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnBus1)
                            .addComponent(BtnBus2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnOr)
                    .addComponent(BtnMC))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JTACKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTACKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_JTACKeyTyped

    private void BtnEn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEn2ActionPerformed

    private void BtnEn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEn1MouseClicked
        cad=JTA1.getText();
       if(cad.length()>0)
       {   
           cad=cad+" \n";
           Nodo n = new Nodo(cad);
           Nodo m = new Nodo(cad);
           ar.getCol().inserta(n);
           ar.getP1().inserta(m);
           cad=ar.getCol().cadena();
           ar.setNum(ar.getNum() + 1);
           JTAC.setText(cad);
           JTA1.setText(null);
       }
        
    }//GEN-LAST:event_BtnEn1MouseClicked

    private void BtnEn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEn2MouseClicked
       cad=JTA2.getText();
       if(cad.length()>0)
       {
           cad=cad+" \n"+"2";
           Nodo n = new Nodo(cad); 
           Nodo m = new Nodo(cad); 
           ar.getCol().inserta(n);
           ar.getP2().inserta(m);
           cad=ar.getCol().cadena();
           ar.setNum(ar.getNum() + 1);
           JTAC.setText(cad);
           JTA2.setText(null);
       }
       
    }//GEN-LAST:event_BtnEn2MouseClicked

    private void BtnMo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMo1MouseClicked

           cad=ar.getP1().cadena();
           JTAC.setText(cad);

    }//GEN-LAST:event_BtnMo1MouseClicked

    private void BtnMo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMo2MouseClicked

           cad=ar.getP2().cadena();
           JTAC.setText(cad);
  
    }//GEN-LAST:event_BtnMo2MouseClicked

    private void BtnMo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMo1ActionPerformed
       
    }//GEN-LAST:event_BtnMo1ActionPerformed

    private void BtnBus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBus1ActionPerformed
        String bus=JTA1.getText();
        cad=ar.getP1().busca(bus);
        JTAC.setText(cad);
        JTA1.setText(null);
        
    }//GEN-LAST:event_BtnBus1ActionPerformed

    private void BtnMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMCActionPerformed
   
    }//GEN-LAST:event_BtnMCActionPerformed

    private void BtnMCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMCMouseClicked
       cad=ar.getCol().cadena();
       JTAC.setText(cad); 
    }//GEN-LAST:event_BtnMCMouseClicked

    private void BtnBus2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBus2MouseClicked
        String bus=JTA2.getText();
        cad=ar.getP2().busca(bus);
        JTAC.setText(cad);
        JTA2.setText(null);
    }//GEN-LAST:event_BtnBus2MouseClicked

    private void BtnOrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOrMouseClicked
        cad=ar.getCol().ordena();
        JTAC.setText(cad);
    }//GEN-LAST:event_BtnOrMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        r.setObj(ar);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnChat().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBus1;
    private javax.swing.JButton BtnBus2;
    private javax.swing.JButton BtnEn1;
    private javax.swing.JButton BtnEn2;
    private javax.swing.JButton BtnMC;
    private javax.swing.JButton BtnMo1;
    private javax.swing.JButton BtnMo2;
    private javax.swing.JButton BtnOr;
    private javax.swing.JTextArea JTA1;
    private javax.swing.JTextArea JTA2;
    private javax.swing.JTextArea JTAC;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
