package p2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import p1.Ventana;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;

/**
 *
 * @author Arturo Díaz
 *
 * COLA FIFO (Fist Input First Output) - Primero Entra Primero Sale PILA LIFO
 * (Last Input First Input) - Ultimo Entra Primero Sale
 */
public class Principal2 extends javax.swing.JFrame
{
    
    Pila ObjPilaUno = new Pila();
    Pila ObjPilaDos = new Pila();
    Cola ObjCola = new Cola();
    

    String texto = "";
    String fecha;
    String conversacion = "";
    String na, nb;
    
    /**
     * Creates new form NewJFrame
     * @param fecha
     * @param emisor
     * @param receptor
     */
    public Principal2(String fecha, String receptor)
    {
        initComponents();
        jLabel1.setText(p1.Ventana.emisor);
        jLabel2.setText(p1.Ventana.fecha);
        jLabel3.setText(p1.Ventana.receptor);
        
        texto = inter.Archivo.mostrarConversacion(p1.Ventana.emisor, p1.Ventana.fecha, p1.Ventana.receptor);
        jTextArea1.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        enviarA = new javax.swing.JButton();
        enviarB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        conversacionReciente = new javax.swing.JButton();
        conversacionCompleta = new javax.swing.JButton();
        buscarA = new javax.swing.JButton();
        buscarB = new javax.swing.JButton();
        ordenarA = new javax.swing.JButton();
        ordenarB = new javax.swing.JButton();
        conversacionA = new javax.swing.JButton();
        conversacionB = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enviarA.setText("Enviar");
        enviarA.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                enviarAMouseClicked(evt);
            }
        });

        enviarB.setText("Enviar");
        enviarB.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                enviarBMouseClicked(evt);
            }
        });
        enviarB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                enviarBActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane3.setViewportView(jTextPane2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Proyecto");

        conversacionReciente.setText("Conversacion reciente");
        conversacionReciente.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                conversacionRecienteMouseClicked(evt);
            }
        });

        conversacionCompleta.setText("Conversacion completa");
        conversacionCompleta.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                conversacionCompletaMouseClicked(evt);
            }
        });
        conversacionCompleta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                conversacionCompletaActionPerformed(evt);
            }
        });

        buscarA.setText("Buscar");
        buscarA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscarAActionPerformed(evt);
            }
        });

        buscarB.setText("Buscar");
        buscarB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buscarBActionPerformed(evt);
            }
        });

        ordenarA.setText("Ordenar");
        ordenarA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ordenarAActionPerformed(evt);
            }
        });

        ordenarB.setText("Ordenar");
        ordenarB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ordenarBActionPerformed(evt);
            }
        });

        conversacionA.setText("Conversacion");
        conversacionA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                conversacionAActionPerformed(evt);
            }
        });

        conversacionB.setText("Conversacion");
        conversacionB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                conversacionBActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jTextPane3);

        jScrollPane5.setViewportView(jTextPane4);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Proyecto");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("2° Parcial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enviarA)
                            .addComponent(ordenarA))
                        .addGap(18, 18, 18)
                        .addComponent(conversacionA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ordenarB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(conversacionB))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(buscarA)
                        .addGap(42, 42, 42)
                        .addComponent(conversacionCompleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(enviarB)
                        .addGap(18, 18, 18)
                        .addComponent(buscarB)
                        .addGap(24, 24, 24)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(conversacionReciente)
                                .addGap(10, 10, 10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(conversacionReciente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conversacionCompleta)
                    .addComponent(enviarA)
                    .addComponent(buscarA)
                    .addComponent(enviarB)
                    .addComponent(buscarB))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ordenarA)
                    .addComponent(conversacionA)
                    .addComponent(conversacionB)
                    .addComponent(ordenarB))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarAMouseClicked
        // TODO add your handling code here:
        na = jTextPane3.getText();
        texto = jTextPane1.getText();
        fecha = Archivo.fecha();
        Archivo.escrituraArchivo("1**" + texto + "--" + fecha + "||" + na + "&&");
        conversacion = "\n" + conversacion + "\n" + na + "\n" + texto + "\n" + fecha;
        jTextArea1.setText(conversacion);
        ObjPilaUno.insertar("1**" + texto + "--" + fecha + "||" + na + "&&");
        ObjCola.insertar("1**" + texto + "--" + fecha + "||" + na + "&&");
        System.out.println("1**" + texto + "--" + fecha + "||" + na + "&&");
        jTextPane1.setText("");
    }//GEN-LAST:event_enviarAMouseClicked

    private void enviarBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarBMouseClicked
        // TODO add your handling code here:
        nb = jTextPane4.getText();
        texto = jTextPane2.getText();
        fecha = Archivo.fecha();
        Archivo.escrituraArchivo("2**" + texto + "--" + fecha + "||" + nb + "&&");
        conversacion = "\n\t" + conversacion + "\n\t" + nb + "\n\t" + texto + "\n\t" + fecha;
        jTextArea1.setText(conversacion);
        ObjPilaDos.insertar("2**" + texto + "--" + fecha + "||");
        ObjCola.insertar((String) "2**" + texto + "--" + fecha + "||" + nb + "&&");
        System.out.println("2**" + texto + "--" + fecha + "||" + nb + "&&");
        jTextPane2.setText("");
    }//GEN-LAST:event_enviarBMouseClicked

    private void conversacionRecienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conversacionRecienteMouseClicked
        // TODO add your handling code here:
        jTextArea1.setText("");
        ObjCola.imprimir();
        jTextArea1.setText(ObjCola.colaTextoCompleto());
    }//GEN-LAST:event_conversacionRecienteMouseClicked

    private void conversacionCompletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conversacionCompletaMouseClicked
        // TODO add your handling code here:
        String input = Archivo.lecturaArchivo();
        jTextArea1.setText(input);
    }//GEN-LAST:event_conversacionCompletaMouseClicked


    private void ordenarAActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ordenarAActionPerformed
    {//GEN-HEADEREND:event_ordenarAActionPerformed
        // TODO add your handling code here:
        if (ObjPilaUno.ordena()) // Si hay datos en la pila 1, los va a ordenar de acuerdo a la primera letra del mensaje y alfabeticamente.
        {
            jTextArea1.setText(ObjPilaUno.toString(1));
        } else  // Sino hay datos, muestra el mensaje.
        {
            JOptionPane.showMessageDialog(this, "¡No hay mensajes para ordenar!", "Información", WIDTH);
        }
    }//GEN-LAST:event_ordenarAActionPerformed

    private void buscarBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscarBActionPerformed
    {//GEN-HEADEREND:event_buscarBActionPerformed
        // TODO add your handling code here:
        String busca = jTextPane2.getText();  //Guarda en una variable lo que se busca pero sin espacios inecesarios.
        System.out.println("Buscando: " + busca);
        String buscado = (String) ObjPilaDos.buscar(busca);  // Variable que va a guardar el mensaje buscado en la pila.

        if (busca.trim().length() == 0) //Condicional que muestra un mensaje si coloco espacios en blanco.
        {
            JOptionPane.showMessageDialog(this, "¡No hay mensaje que buscar!", "Información", WIDTH);
        } else if (ObjPilaDos.vacia()) //Condicional que muestra un mensaje si la pila2 esta vacia.
        {
            JOptionPane.showMessageDialog(this, "¡Bandeja de salida vacía!", "Información", WIDTH);
        } else if (buscado == null) //Condicional que muestra un mensaje si no se encuentra el mensaje.
        {
            JOptionPane.showMessageDialog(this, "¡No se encontro el mensaje!", "Información", WIDTH);
        } else // Si no se cumple lo anterior, muestra el mensaje.
        {
            jTextArea1.setText(buscado);
        }
        jTextPane2.setText("");
    }//GEN-LAST:event_buscarBActionPerformed

    private void buscarAActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buscarAActionPerformed
    {//GEN-HEADEREND:event_buscarAActionPerformed
        // TODO add your handling code here:
        String busca = jTextPane1.getText();  //Guarda en una variable lo que se busca pero sin espacios inecesarios.
        System.out.println("Buscando: " + busca);
        String buscado = (String) ObjPilaUno.buscar(busca);  // Variable que va a guardar el mensaje buscado en la pila.

        if (busca.trim().length() == 0) //Condicional que muestra un mensaje si coloco espacios en blanco.
        {
            JOptionPane.showMessageDialog(this, "¡No hay mensaje que buscar!", "Información", WIDTH);
        } else if (ObjPilaUno.vacia()) //Condicional que muestra un mensaje si la pila2 esta vacia.
        {
            JOptionPane.showMessageDialog(this, "¡Bandeja de salida vacía!", "Información", WIDTH);
        } else if (buscado == null) //Condicional que muestra un mensaje si no se encuentra el mensaje.
        {
            JOptionPane.showMessageDialog(this, "¡No se encontro el mensaje!", "Información", WIDTH);
        } else // Si no se cumple lo anterior, muestra el mensaje.
        {
            jTextArea1.setText(buscado);
        }
        jTextPane1.setText("");
    }//GEN-LAST:event_buscarAActionPerformed

    private void conversacionAActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_conversacionAActionPerformed
    {//GEN-HEADEREND:event_conversacionAActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        ObjCola.imprimir(1);
        jTextArea1.setText(ObjCola.colaTextoCompleto());
    }//GEN-LAST:event_conversacionAActionPerformed

    private void conversacionBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_conversacionBActionPerformed
    {//GEN-HEADEREND:event_conversacionBActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        ObjCola.imprimir(2);
        jTextArea1.setText(ObjCola.colaTextoCompleto());
    }//GEN-LAST:event_conversacionBActionPerformed

    private void conversacionCompletaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_conversacionCompletaActionPerformed
    {//GEN-HEADEREND:event_conversacionCompletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conversacionCompletaActionPerformed

    private void ordenarBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ordenarBActionPerformed
    {//GEN-HEADEREND:event_ordenarBActionPerformed
        // TODO add your handling code here:
        if (ObjPilaDos.ordena()) // Si hay datos en la pila 2, los va a ordenar de acuerdo a la primera letra del mensaje y alfabeticamente.
        {
            jTextArea1.setText(ObjPilaDos.toString(2));
        } else  // Sino hay datos, muestra el mensaje.
        {
            JOptionPane.showMessageDialog(this, "¡No hay mensajes para ordenar!", "Información", WIDTH);
        }
    }//GEN-LAST:event_ordenarBActionPerformed

    private void enviarBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_enviarBActionPerformed
    {//GEN-HEADEREND:event_enviarBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarBActionPerformed

    /**
     * @param fecha
     * @param emisor
     * @param receptor
     */
    public static void main(final String fecha, final String receptor)
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /**
         * Al iniciar, se ejecutara el codigo Archivo/nuevoArchivo()
         */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new Principal2(fecha, receptor).setVisible(true);
                Archivo.nuevoArchivo();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarA;
    private javax.swing.JButton buscarB;
    private javax.swing.JButton conversacionA;
    private javax.swing.JButton conversacionB;
    private javax.swing.JButton conversacionCompleta;
    private javax.swing.JButton conversacionReciente;
    private javax.swing.JButton enviarA;
    private javax.swing.JButton enviarB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JButton ordenarA;
    private javax.swing.JButton ordenarB;
    // End of variables declaration//GEN-END:variables
}
